# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 819)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.importImgBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importImgBtn.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.importImgBtn.setObjectName("importImgBtn")
        self.imageUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.imageUrl.setGeometry(QtCore.QRect(130, 10, 731, 31))
        self.imageUrl.setObjectName("imageUrl")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(20, 60, 841, 701))
        self.imageLabel.setObjectName("imageLabel")
        self.objectDetectionRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.objectDetectionRadioBtn.setGeometry(QtCore.QRect(890, 50, 181, 20))
        self.objectDetectionRadioBtn.setChecked(True)
        self.objectDetectionRadioBtn.setObjectName("objectDetectionRadioBtn")
        self.licensePlateRadioBtn = QtWidgets.QRadioButton(self.centralwidget)
        self.licensePlateRadioBtn.setGeometry(QtCore.QRect(890, 80, 181, 20))
        self.licensePlateRadioBtn.setChecked(False)
        self.licensePlateRadioBtn.setObjectName("licensePlateRadioBtn")
        self.executeFunction = QtWidgets.QPushButton(self.centralwidget)
        self.executeFunction.setGeometry(QtCore.QRect(890, 120, 93, 28))
        self.executeFunction.setObjectName("executeFunction")
        self.informationError = QtWidgets.QLabel(self.centralwidget)
        self.informationError.setGeometry(QtCore.QRect(900, 10, 341, 31))
        self.informationError.setText("")
        self.informationError.setObjectName("informationError")
        self.resultTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTableWidget.setGeometry(QtCore.QRect(890, 160, 361, 601))
        self.resultTableWidget.setColumnCount(0)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.importImgBtn.setText(_translate("MainWindow", "Chọn ảnh"))
        self.imageLabel.setText(_translate("MainWindow", "Ảnh"))
        self.objectDetectionRadioBtn.setText(_translate("MainWindow", "Đếm số lượng đối tượng"))
        self.licensePlateRadioBtn.setText(_translate("MainWindow", "Đọc biển số xe"))
        self.executeFunction.setText(_translate("MainWindow", "Thực hiện"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
